name: flighttickets
description: Flight Tickets List App


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:

  flutter:
    sdk: flutter
  flutter_localizations:
      sdk: flutter


  path_provider: ^1.6.5
  cupertino_icons: ^0.1.2
  intl:
  flutter_rounded_date_picker: ^1.0.4
  animated_text_kit: ^2.0.1
  firebase_core: ^0.4.4+3
  firebase_auth: ^0.16.0
  cloud_firestore: ^0.13.5
  modal_progress_hud: ^0.1.3



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  fonts:
    - family: Helvetica
      fonts:
        - asset: assets/fonts/HelveticaBold.ttf
        - asset: assets/fonts/HelveticaRegular.ttf


  assets:
    - assets/images/
